// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'pleaseLinkYourOwnFirebaseCLI',
    appId: '1:231188139278:web:078e67f33b0aacc9a1db5f',
    messagingSenderId: '231188139278',
    projectId: 'lingopanda-assignment-6c490',
    authDomain: 'lingopanda-assignment-6c490.firebaseapp.com',
    storageBucket: 'lingopanda-assignment-6c490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'pleaseLinkYourOwnFirebaseCLI',
    appId: '1:231188139278:android:38ca635a79479506a1db5f',
    messagingSenderId: '231188139278',
    projectId: 'lingopanda-assignment-6c490',
    storageBucket: 'lingopanda-assignment-6c490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'pleaseLinkYourOwnFirebaseCLI',
    appId: '1:231188139278:ios:391a9ebcbb3ce241a1db5f',
    messagingSenderId: '231188139278',
    projectId: 'lingopanda-assignment-6c490',
    storageBucket: 'lingopanda-assignment-6c490.appspot.com',
    iosBundleId: 'com.example.lingopandaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'pleaseLinkYourOwnFirebaseCLI',
    appId: '1:231188139278:ios:391a9ebcbb3ce241a1db5f',
    messagingSenderId: '231188139278',
    projectId: 'lingopanda-assignment-6c490',
    storageBucket: 'lingopanda-assignment-6c490.appspot.com',
    iosBundleId: 'com.example.lingopandaAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'pleaseLinkYourOwnFirebaseCLI',
    appId: '1:231188139278:web:ab708c7d3756baf4a1db5f',
    messagingSenderId: '231188139278',
    projectId: 'lingopanda-assignment-6c490',
    authDomain: 'lingopanda-assignment-6c490.firebaseapp.com',
    storageBucket: 'lingopanda-assignment-6c490.appspot.com',
  );
}
